// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Program struct {
	ID           pgtype.UUID
	Title        string
	StartAt      pgtype.Timestamptz
	EndAt        pgtype.Timestamptz
	PlatformName string
	ImageUrl     pgtype.Text
	LinkUrl      pgtype.Text
	CreatedAt    pgtype.Timestamptz
}
