// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// API使用量追跡（YouTube等）
type ApiQuotaUsage struct {
	ID           pgtype.UUID        `json:"id"`
	Date         pgtype.Date        `json:"date"`
	PlatformID   string             `json:"platform_id"`
	Endpoint     string             `json:"endpoint"`
	QuotaCost    int32              `json:"quota_cost"`
	RequestCount int32              `json:"request_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// タイムライン項目（動画/配信/予定等）
type Event struct {
	ID              pgtype.UUID `json:"id"`
	PlatformID      string      `json:"platform_id"`
	SourceID        pgtype.UUID `json:"source_id"`
	ExternalEventID string      `json:"external_event_id"`
	// live=配信中, scheduled=予定, video=アーカイブ動画, premiere=プレミア公開
	Type        string             `json:"type"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Url         string             `json:"url"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	// JSON形式の統計情報 {"views": 123, "likes": 45, "comments": 67}
	Metrics   []byte             `json:"metrics"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Video/stream duration in HH:MM:SS or MM:SS format
	Duration pgtype.Text `json:"duration"`
}

type PlanLimit struct {
	PlanType      string             `json:"plan_type"`
	MaxChannels   int32              `json:"max_channels"`
	DisplayName   string             `json:"display_name"`
	PriceMonthly  pgtype.Int4        `json:"price_monthly"`
	HasFavorites  bool               `json:"has_favorites"`
	HasDeviceSync bool               `json:"has_device_sync"`
	Description   pgtype.Text        `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// 配信プラットフォーム（YouTube, Twitch等）
type Platform struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// チャンネル/配信者の情報
type Source struct {
	ID                pgtype.UUID        `json:"id"`
	PlatformID        string             `json:"platform_id"`
	ExternalID        string             `json:"external_id"`
	Handle            pgtype.Text        `json:"handle"`
	DisplayName       pgtype.Text        `json:"display_name"`
	ThumbnailUrl      pgtype.Text        `json:"thumbnail_url"`
	UploadsPlaylistID pgtype.Text        `json:"uploads_playlist_id"`
	LastFetchedAt     pgtype.Timestamptz `json:"last_fetched_at"`
	// ok=正常, not_found=削除/非公開, suspended=BAN, error=取得エラー
	FetchStatus string             `json:"fetch_status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	// Apple Podcasts URL (for podcast platform only)
	ApplePodcastUrl pgtype.Text `json:"apple_podcast_url"`
}

// チャンネル優先度管理（バッチ処理最適化用）
type SourcePriority struct {
	SourceID        pgtype.UUID    `json:"source_id"`
	SubscriberCount int32          `json:"subscriber_count"`
	PopularityRatio pgtype.Numeric `json:"popularity_ratio"`
	// high=1h更新, medium=3h更新, low=6h更新
	PriorityLevel string `json:"priority_level"`
	// 更新間隔（分）: high=60, medium=180, low=360
	UpdateIntervalMinutes int32              `json:"update_interval_minutes"`
	LastCalculatedAt      pgtype.Timestamptz `json:"last_calculated_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// 更新スケジュール管理
type UpdateSchedule struct {
	ID            pgtype.UUID        `json:"id"`
	SourceID      pgtype.UUID        `json:"source_id"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	PriorityLevel string             `json:"priority_level"`
	// pending=待機中, running=実行中, completed=完了, failed=失敗
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             int64              `json:"id"`
	FirebaseUid    string             `json:"firebase_uid"`
	PlanType       string             `json:"plan_type"`
	Email          pgtype.Text        `json:"email"`
	DisplayName    pgtype.Text        `json:"display_name"`
	PhotoUrl       pgtype.Text        `json:"photo_url"`
	IsAnonymous    bool               `json:"is_anonymous"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// ユーザーの購読情報
type UserSubscription struct {
	UserID         int64              `json:"user_id"`
	SourceID       pgtype.UUID        `json:"source_id"`
	Enabled        bool               `json:"enabled"`
	Priority       int32              `json:"priority"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	IsFavorite     bool               `json:"is_favorite"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
}
