// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProgram = `-- name: CreateProgram :one
INSERT INTO programs (
  title, start_at, end_at, platform_name, image_url, link_url
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, title, start_at, end_at, platform_name, image_url, link_url, created_at
`

type CreateProgramParams struct {
	Title        string
	StartAt      pgtype.Timestamptz
	EndAt        pgtype.Timestamptz
	PlatformName string
	ImageUrl     pgtype.Text
	LinkUrl      pgtype.Text
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, createProgram,
		arg.Title,
		arg.StartAt,
		arg.EndAt,
		arg.PlatformName,
		arg.ImageUrl,
		arg.LinkUrl,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartAt,
		&i.EndAt,
		&i.PlatformName,
		&i.ImageUrl,
		&i.LinkUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, title, start_at, end_at, platform_name, image_url, link_url, created_at FROM programs
ORDER BY start_at ASC
`

func (q *Queries) ListPrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.Query(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Program
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartAt,
			&i.EndAt,
			&i.PlatformName,
			&i.ImageUrl,
			&i.LinkUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
